version: '3.4'

services:
  app:
    build:
      context: .
      target: runtime
    ports:
      - 8008:8000

  debug:
    build:
      context: .
      target: build
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    
  tests:
    build:
      context: .
      target: test
    volumes:
      - ./test/output:/app/output
  
  load:
    build:
      context: .
      target: load
    volumes:
      - ./data:/app/data